INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('1', 'ÁO-NỮ', 'NỮ', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('2', 'QUẦN-NỮ', 'NỮ', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('3', 'ĐẦM & VÁY-NỮ', 'NỮ', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('4', 'MẶC NHÀ-NỮ', 'NỮ', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('5', 'MẶC NGOÀI-NỮ', 'NỮ', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('6', 'ÁO-NAM', 'NAM', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('7', 'QUẦN-NAM', 'NAM', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('8', 'MẶC NHÀ-NAM', 'NAM', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('9', 'MẶC NGOÀI-NAM', 'NAM', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('10', 'ÁO-TRẺ', 'TRẺ EM', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('11', 'QUẦN-TRẺ', 'TRẺ EM', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('12', 'MẶC NHÀ-TRẺ', 'TRẺ EM', '1');
INSERT INTO `shopbuy_service`.`category` (`ID`, `NAME`, `GENDER`, `IS_SHOWN`) VALUES ('13', 'MẶC NGOÀI-TRẺ', 'TRẺ EM', '1');