INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('1', 'Áo Thun', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('2', 'Áo Thun Họa Tiết', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('3', 'Áo Sơ Mi', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('4', 'Áo Len', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('5', 'Quần Short', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('6', 'Quần Jeans', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('7', 'Quần Nỉ', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('8', 'Quần Tây', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('9', 'Đầm & Jumpsuit', '3', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('10', 'Váy', '3', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('11', 'Quần Easy & Relaxed', '4', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('12', 'Đồ Mặc Nhà & Pyjama', '4', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('13', 'Áo Blouson & Áo Parka', '5', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('14', 'Áo Khoác & Áo Blazer', '5', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('15', 'Áo Choàng Dáng Dài', '5', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('16', 'Áo Polo', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('17', 'Áo Thun', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('18', 'Áo Sơ Mi Công Sở', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('19', 'Áo Len', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('20', 'Quần Tây', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('21', 'Quần Jean & Quần Jean Màu', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('22', 'Quần Short', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('23', 'Quần Nỉ', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('24', 'Đồ Mặc Nhà & Pyjama', '8', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('25', 'Quần Easy & Relaxed', '8', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('26', 'Áo Blouson & Áo Parka', '9', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('27', 'Áo Khoác AirSense', '9', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('28', 'Áo Choàng Dáng Dài', '9', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('29', 'Áo Thun In Họa Tiết', '10', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('30', 'Áo Thun + Áo Polo', '10', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('31', 'Áo Sơ Mi & Áo Kiểu', '10', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('32', 'Quần Short', '11', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('33', 'Quần Dài', '11', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('34', 'Đồ Mặc Nhà & Pyjama', '12', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('35', 'Áo Blouson & Áo Parka', '13', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('36', 'Áo Khoác', '13', '1');
