INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('1', 'Áo Nữ - Thun', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('2', 'Áo Nữ - Thun Họa Tiết', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('3', 'Áo Nữ - Sơ Mi', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('4', 'Áo Nữ - Len', '1', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('5', 'Quần Nữ - Short', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('6', 'Quần Nữ - Jeans', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('7', 'Quần Nữ - Nỉ', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('8', 'Quần Nữ - Tây', '2', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('9', 'Đầm & Jumpsuit', '3', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('10', 'Váy', '3', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('11', 'Nữ Mặc Nhà - Quần Easy & Relaxed', '4', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('12', 'Nữ Mặc Nhà & Pyjama', '4', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('13', 'Nữ Mặc Ngoài - Áo Blouson & Áo Parka', '5', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('14', 'Nữ Mặc Ngoài - Áo Khoác & Áo Blazer', '5', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('15', 'Nữ Mặc Ngoài - Áo Choàng Dáng Dài', '5', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('16', 'Áo Nam - Polo', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('17', 'Áo Nam - Thun', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('18', 'Áo Nam - Sơ Mi Công Sở', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('19', 'Áo Nam - Áo Len', '6', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('20', 'Quần Nam - Tây', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('21', 'Quần Nam - Quần Jean & Quần Jean Màu', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('22', 'Quần Nam - Quần Short', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('23', 'Quần Nam - Quần Nỉ', '7', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('24', 'Nam Mặc Nhà - Pyjama', '8', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('25', 'Nam Mặc Nhà - Quần Easy & Relaxed', '8', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('26', 'Nam Mặc Ngoài  - Áo Blouson & Áo Parka', '9', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('27', 'Nam Mặc Ngoài  - Áo Khoác AirSense', '9', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('28', 'Nam Mặc Ngoài  - Áo Choàng Dáng Dài', '9', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('29', 'Áo Trẻ - Thun In Họa Tiết', '10', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('30', 'Áo Trẻ - Thun + Áo Polo', '10', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('31', 'Áo Trẻ - Áo Sơ Mi & Áo Kiểu', '10', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('32', 'Quần Trẻ - Quần Short', '11', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('33', 'Quần Trẻ - Quần Dài', '11', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('34', 'Trẻ Mặc Nhà & Pyjama', '12', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('35', 'Trẻ Mặc Ngoài - Quần - Áo Blouson ', '13', '1');
INSERT INTO `shopbuy_service`.`sub_category` (`ID`, `NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('36', 'Trẻ Mặc Ngoài - Áo Khoác', '13', '1');
